-- Purpose: store KOSPI/KOSDAQ market regime monitor snapshots for quant serving.
-- Owner: quant-serving
-- Grain: one latest-upserted row per trade_date.
-- PK: id identity.
-- Unique: trade_date. KOSPI and KOSDAQ route decisions are stored separately.
-- Indexes: latest lookup by trade_date DESC, updated_at DESC.
-- Backfill: run the API refresh job after index and market_daily_price data are available.
-- Rollback: DROP INDEX idx_quant_market_regime_snapshot_latest; DROP TABLE quant_market_regime_snapshot;
-- Validation: SELECT trade_date, combined_regime, allowed_strategy FROM quant_market_regime_snapshot ORDER BY trade_date DESC LIMIT 5;
-- Sensitivity: market/index-derived public data only; no user data.

CREATE TABLE IF NOT EXISTS quant_market_regime_snapshot (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trade_date       DATE          NOT NULL,
    cache_date       DATE          NOT NULL,
    live_kospi       NUMERIC(18,2) NOT NULL,
    live_kosdaq      NUMERIC(18,2) NOT NULL,
    kospi_regime     VARCHAR(20)   NOT NULL,
    kosdaq_regime    VARCHAR(20)   NOT NULL,
    kospi_allowed_strategy  VARCHAR(50)  NOT NULL,
    kosdaq_allowed_strategy VARCHAR(50)  NOT NULL,
    kospi_risk_budget       NUMERIC(8,6) NOT NULL,
    kosdaq_risk_budget      NUMERIC(8,6) NOT NULL,
    combined_regime  VARCHAR(20)   NOT NULL,
    allowed_strategy VARCHAR(50)   NOT NULL,
    confidence       NUMERIC(8,6)  NOT NULL,
    risk_budget      NUMERIC(8,6)  NOT NULL,
    bull_score       INTEGER       NOT NULL,
    bear_score       INTEGER       NOT NULL,
    stress_score     INTEGER       NOT NULL,
    breadth_ma20     NUMERIC(8,6),
    breadth_ma60     NUMERIC(8,6),
    volatility_20    NUMERIC(12,8),
    liquidity_trend  NUMERIC(12,8),
    updated_at       TIMESTAMP     NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_quant_market_regime_snapshot_trade_date UNIQUE (trade_date)
);

CREATE INDEX IF NOT EXISTS idx_quant_market_regime_snapshot_latest
    ON quant_market_regime_snapshot (trade_date DESC, updated_at DESC);
