-- Quant intraday realtime monitoring persistence.
-- Purpose: persist 1-minute bars, candidate state snapshots, and signal events for realtime quant monitoring.
-- Owner: quant-serving
-- Grain:
--   quant_intraday_bar = one asset per 1-minute KST bar.
--   quant_intraday_candidate_snapshot = one model/asset/current state snapshot per tick.
--   quant_intraday_signal_event = one model/asset/state transition event.
-- PK: identity id on each table.
-- FK: none yet; stock and model reference tables are not fully canonicalized in prod.
-- Unique:
--   quant_intraday_bar unique on (asset_code, bar_time).
--   quant_intraday_candidate_snapshot unique on (model_code, signal_date, asset_code).
-- Indexes: asset/time, model/date/state, event model/time.
-- Backfill: none required; realtime scheduler writes new rows only.
-- Rollback: DROP INDEX idx_qise_model_time; DROP TABLE quant_intraday_signal_event; DROP INDEX idx_qics_model_state; DROP TABLE quant_intraday_candidate_snapshot; DROP INDEX idx_qib_asset_time; DROP TABLE quant_intraday_bar; ALTER TABLE quant_live_paper_candidate ALTER COLUMN decision TYPE VARCHAR(10);
-- Validation: SELECT model_code, state, COUNT(*) FROM quant_intraday_candidate_snapshot GROUP BY model_code, state; SELECT COUNT(*) FROM quant_intraday_bar; SELECT model_code, event_type, COUNT(*) FROM quant_intraday_signal_event GROUP BY model_code, event_type;
-- Sensitivity: simulated market-monitoring records only; no real account, user, or order data.

ALTER TABLE quant_live_paper_candidate
    ALTER COLUMN decision TYPE VARCHAR(20);

CREATE TABLE IF NOT EXISTS quant_intraday_bar (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_code      VARCHAR(20)  NOT NULL,
    asset_name      VARCHAR(100),
    market          VARCHAR(20),
    bar_time        TIMESTAMP    NOT NULL,
    open_price      NUMERIC(18,4),
    high_price      NUMERIC(18,4),
    low_price       NUMERIC(18,4),
    close_price     NUMERIC(18,4) NOT NULL,
    volume          BIGINT       DEFAULT 0,
    trade_amount    BIGINT       DEFAULT 0,
    change_rate     NUMERIC(12,6),
    source          VARCHAR(60)  NOT NULL,
    created_at      TIMESTAMP    DEFAULT NOW(),
    CONSTRAINT uq_quant_intraday_bar UNIQUE (asset_code, bar_time)
);
CREATE INDEX IF NOT EXISTS idx_qib_asset_time
    ON quant_intraday_bar(asset_code, bar_time DESC);

CREATE TABLE IF NOT EXISTS quant_intraday_candidate_snapshot (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_code          VARCHAR(50)  NOT NULL,
    signal_date         DATE         NOT NULL,
    asset_code          VARCHAR(20)  NOT NULL,
    asset_name          VARCHAR(100),
    market              VARCHAR(20),
    state               VARCHAR(20)  NOT NULL,
    reason              TEXT,
    current_price       NUMERIC(18,4),
    change_rate         NUMERIC(12,6),
    trade_amount        BIGINT       DEFAULT 0,
    source              VARCHAR(60)  NOT NULL,
    observed_at         TIMESTAMP    NOT NULL DEFAULT NOW(),
    created_at          TIMESTAMP    DEFAULT NOW(),
    updated_at          TIMESTAMP    DEFAULT NOW(),
    CONSTRAINT uq_quant_intraday_candidate_snapshot UNIQUE (model_code, signal_date, asset_code)
);
CREATE INDEX IF NOT EXISTS idx_qics_model_state
    ON quant_intraday_candidate_snapshot(model_code, signal_date DESC, state, updated_at DESC);

CREATE TABLE IF NOT EXISTS quant_intraday_signal_event (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_code      VARCHAR(50)  NOT NULL,
    signal_date     DATE         NOT NULL,
    asset_code      VARCHAR(20)  NOT NULL,
    asset_name      VARCHAR(100),
    event_type      VARCHAR(30)  NOT NULL,
    from_state      VARCHAR(20),
    to_state        VARCHAR(20)  NOT NULL,
    reason          TEXT,
    observed_price  NUMERIC(18,4),
    change_rate     NUMERIC(12,6),
    source          VARCHAR(60)  NOT NULL,
    observed_at     TIMESTAMP    NOT NULL DEFAULT NOW(),
    created_at      TIMESTAMP    DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_qise_model_time
    ON quant_intraday_signal_event(model_code, observed_at DESC);
