-- Quant live paper trading persistence.
-- This stores simulated candidates, positions, and trades only.
-- Purpose: persist automatic live quant paper candidates, open positions, and simulated trades.
-- Owner: quant-serving
-- Grain: candidate = one model/date/asset signal, position = one simulated holding, trade = one simulated fill event.
-- PK: identity id on each table.
-- Unique: candidate unique on (model_code, signal_date, asset_code); one OPEN position per (model_code, asset_code).
-- Indexes: model/date candidate lookup, model/status position lookup, model/fill_time trade lookup.
-- Backfill: none required; rows are generated by LiveQuantPaperTradingScheduler or manual run API.
-- Rollback: DROP INDEX idx_qlpt_model_time; DROP TABLE quant_live_paper_trade; DROP INDEX idx_qlpp_model_status; DROP INDEX uq_qlpp_open_position; DROP TABLE quant_live_paper_position; DROP INDEX idx_qlpc_model_date; DROP TABLE quant_live_paper_candidate;
-- Validation: SELECT model_code, COUNT(*) FROM quant_live_paper_candidate GROUP BY model_code; SELECT model_code, status, COUNT(*) FROM quant_live_paper_position GROUP BY model_code, status; SELECT model_code, side, COUNT(*) FROM quant_live_paper_trade GROUP BY model_code, side;
-- Sensitivity: simulated market-trading records only; no real account or user order data.

CREATE TABLE IF NOT EXISTS quant_live_paper_candidate (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_code          VARCHAR(50)  NOT NULL,
    signal_date         DATE         NOT NULL,
    market_date         DATE         NOT NULL,
    asset_code          VARCHAR(20)  NOT NULL,
    asset_name          VARCHAR(100),
    decision            VARCHAR(10)  NOT NULL,
    reason              TEXT,
    signal_price        NUMERIC(18,4),
    expected_return_pct NUMERIC(12,6),
    source              VARCHAR(60)  NOT NULL,
    created_at          TIMESTAMP    DEFAULT NOW(),
    updated_at          TIMESTAMP    DEFAULT NOW(),
    CONSTRAINT uq_quant_live_paper_candidate UNIQUE (model_code, signal_date, asset_code)
);
CREATE INDEX IF NOT EXISTS idx_qlpc_model_date
    ON quant_live_paper_candidate(model_code, signal_date DESC);

CREATE TABLE IF NOT EXISTS quant_live_paper_position (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_code  VARCHAR(50)  NOT NULL,
    asset_code  VARCHAR(20)  NOT NULL,
    asset_name  VARCHAR(100),
    entry_time  TIMESTAMP    NOT NULL,
    entry_price NUMERIC(18,4) NOT NULL,
    quantity    BIGINT       NOT NULL,
    status      VARCHAR(10)  NOT NULL DEFAULT 'OPEN',
    created_at  TIMESTAMP    DEFAULT NOW(),
    updated_at  TIMESTAMP    DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_qlpp_open_position
    ON quant_live_paper_position(model_code, asset_code)
    WHERE status = 'OPEN';
CREATE INDEX IF NOT EXISTS idx_qlpp_model_status
    ON quant_live_paper_position(model_code, status, entry_time DESC);

CREATE TABLE IF NOT EXISTS quant_live_paper_trade (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_code          VARCHAR(50)  NOT NULL,
    position_id         BIGINT,
    asset_code          VARCHAR(20)  NOT NULL,
    asset_name          VARCHAR(100),
    side                VARCHAR(10)  NOT NULL,
    fill_time           TIMESTAMP    NOT NULL,
    signal_price        NUMERIC(18,4),
    fill_price          NUMERIC(18,4) NOT NULL,
    quantity            BIGINT       NOT NULL,
    amount              BIGINT       NOT NULL,
    realized_return_pct NUMERIC(12,6),
    reason              TEXT,
    source              VARCHAR(60)  NOT NULL,
    created_at          TIMESTAMP    DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_qlpt_model_time
    ON quant_live_paper_trade(model_code, fill_time DESC);
