import React from "react";
import RankingTable from "./components/RankingTable";

function BuyingList() {
  const mockData = [
    {
      rank: 1,
      name: "삼성전자",
      todayAmount: "2,450",
      todayVolume: "3,120",
      yesterdayAmount: "2,100",
      yesterdayVolume: "2,900",
      weekAmount: "11,420",
    },
    {
      rank: 2,
      name: "SK하이닉스",
      todayAmount: "1,820",
      todayVolume: "980",
      yesterdayAmount: "1,500",
      yesterdayVolume: "870",
      weekAmount: "9,820",
    },
    {
      rank: 3,
      name: "현대차",
      todayAmount: "1,120",
      todayVolume: "450",
      yesterdayAmount: "980",
      yesterdayVolume: "410",
      weekAmount: "7,200",
    },
    {
      rank: 4,
      name: "LG에너지솔루션",
      todayAmount: "980",
      todayVolume: "210",
      yesterdayAmount: "860",
      yesterdayVolume: "180",
      weekAmount: "6,540",
    },
    {
      rank: 5,
      name: "KB금융",
      todayAmount: "850",
      todayVolume: "640",
      yesterdayAmount: "720",
      yesterdayVolume: "600",
      weekAmount: "5,120",
    },
    {
      rank: 6,
      name: "POSCO홀딩스",
      todayAmount: "760",
      todayVolume: "380",
      yesterdayAmount: "690",
      yesterdayVolume: "340",
      weekAmount: "4,850",
    },
    {
      rank: 7,
      name: "카카오",
      todayAmount: "620",
      todayVolume: "920",
      yesterdayAmount: "580",
      yesterdayVolume: "880",
      weekAmount: "4,210",
    },
    {
      rank: 8,
      name: "고려아연",
      todayAmount: "580",
      todayVolume: "110",
      yesterdayAmount: "510",
      yesterdayVolume: "90",
      weekAmount: "3,950",
    },
    {
      rank: 9,
      name: "삼성SDI",
      todayAmount: "520",
      todayVolume: "340",
      yesterdayAmount: "470",
      yesterdayVolume: "300",
      weekAmount: "3,620",
    },
    {
      rank: 10,
      name: "두산에너빌리티",
      todayAmount: "480",
      todayVolume: "2,300",
      yesterdayAmount: "420",
      yesterdayVolume: "2,100",
      weekAmount: "3,410",
    },
    {
      rank: 11,
      name: "우리금융지주",
      todayAmount: "450",
      todayVolume: "3,200",
      yesterdayAmount: "390",
      yesterdayVolume: "3,000",
      weekAmount: "3,100",
    },
    {
      rank: 12,
      name: "신한지주",
      todayAmount: "410",
      todayVolume: "560",
      yesterdayAmount: "370",
      yesterdayVolume: "520",
      weekAmount: "2,980",
    },
    {
      rank: 13,
      name: "LG화학",
      todayAmount: "390",
      todayVolume: "270",
      yesterdayAmount: "350",
      yesterdayVolume: "250",
      weekAmount: "2,740",
    },
    {
      rank: 14,
      name: "NAVER",
      todayAmount: "360",
      todayVolume: "430",
      yesterdayAmount: "320",
      yesterdayVolume: "400",
      weekAmount: "2,600",
    },
    {
      rank: 15,
      name: "삼성바이오로직스",
      todayAmount: "340",
      todayVolume: "150",
      yesterdayAmount: "300",
      yesterdayVolume: "140",
      weekAmount: "2,420",
    },
    {
      rank: 16,
      name: "하이브",
      todayAmount: "310",
      todayVolume: "220",
      yesterdayAmount: "280",
      yesterdayVolume: "200",
      weekAmount: "2,210",
    },
    {
      rank: 17,
      name: "KT",
      todayAmount: "290",
      todayVolume: "510",
      yesterdayAmount: "260",
      yesterdayVolume: "480",
      weekAmount: "2,050",
    },
    {
      rank: 18,
      name: "대한항공",
      todayAmount: "270",
      todayVolume: "680",
      yesterdayAmount: "240",
      yesterdayVolume: "640",
      weekAmount: "1,920",
    },
    {
      rank: 19,
      name: "현대모비스",
      todayAmount: "250",
      todayVolume: "190",
      yesterdayAmount: "220",
      yesterdayVolume: "170",
      weekAmount: "1,780",
    },
    {
      rank: 20,
      name: "롯데케미칼",
      todayAmount: "230",
      todayVolume: "260",
      yesterdayAmount: "200",
      yesterdayVolume: "240",
      weekAmount: "1,650",
    },
  ];

  return (
    <>
      <h1 className="text-xl font-bold mb-6">순매수 상위 종목</h1>
      <RankingTable data={mockData} />
    </>
  );
}

export default BuyingList;
