import type { QuantDecision, QuantKpi, QuantModelSummary, QuantReportSummary } from "./quantTypes";

export const quantAsOf = "2026.05.28 14:25";

export const quantKpis: QuantKpi[] = [
  {
    id: "look",
    label: "오늘 살펴볼 종목",
    value: "23개",
    hint: "전일 대비",
    delta: "▲ 4",
    direction: "down",
  },
  {
    id: "caution",
    label: "조심 신호",
    value: "8개",
    hint: "전일 대비",
    delta: "▲ 2",
    direction: "up",
  },
  {
    id: "performance",
    label: "모델 검증 수익률",
    value: "+6.42%",
    hint: "최근 1개월 모델 기준",
    delta: "벤치마크 +1.87%",
    direction: "up",
  },
  {
    id: "reports",
    label: "오늘 리포트",
    value: "5건",
    hint: "오늘 업데이트",
    delta: "2건",
    direction: "flat",
  },
];

export const quantModels: QuantModelSummary[] = [
  {
    code: "momentum-earnings",
    name: "모멘텀 모델",
    plainName: "실적과 가격 흐름이 같이 좋아지는 종목",
    description: "실적 개선, 거래대금, 가격 추세가 같은 방향으로 움직이는지 확인합니다.",
    marketMode: "상승장 모델",
    status: "정상 운영",
    signalStrength: "높음",
    focus: ["실적 개선", "거래대금", "가격 추세"],
    todayCount: 11,
  },
  {
    code: "value-recovery",
    name: "가치 모델",
    plainName: "가격 부담이 낮고 회복 여지가 있는 종목",
    description: "기업의 기초 체력 대비 현재 가격이 과하게 낮은지 살펴봅니다.",
    marketMode: "횡보장 모델",
    status: "정상 운영",
    signalStrength: "보통",
    focus: ["저평가", "이익 안정성", "현금흐름"],
    todayCount: 7,
  },
  {
    code: "risk-control",
    name: "하락장 모델",
    plainName: "손실 위험을 먼저 줄이는 종목 판단",
    description: "변동성, 수급 악화, 지수 흐름을 보고 조심해야 할 종목을 걸러냅니다.",
    marketMode: "하락장 모델",
    status: "관찰 중",
    signalStrength: "보통",
    focus: ["변동성", "수급 악화", "지수 흐름"],
    todayCount: 5,
  },
];

export const quantDecisions: QuantDecision[] = [
  {
    assetCode: "000660",
    assetName: "SK하이닉스",
    market: "KOSPI",
    badgeText: "SK",
    badgeTone: "red",
    modelNames: ["모멘텀 모델", "가치 모델"],
    modelLabel: "여러 모델",
    decisionLabel: "살펴볼 종목",
    decisionCode: "BUY",
    reasonBullets: ["실적 모멘텀 강함", "반도체 수급 개선"],
    cautionBullets: ["단기 변동성 확대 가능성", "글로벌 금리 불확실성"],
  },
  {
    assetCode: "005930",
    assetName: "삼성전자",
    market: "KOSPI",
    badgeText: "삼",
    badgeTone: "blue",
    modelNames: ["가치 모델"],
    modelLabel: "횡보장 모델",
    decisionLabel: "살펴볼 종목",
    decisionCode: "BUY",
    reasonBullets: ["메모리 가격 반등", "현금흐름 개선"],
    cautionBullets: ["모바일 수요 회복 지연", "환율 변동성"],
  },
  {
    assetCode: "005380",
    assetName: "현대차",
    market: "KOSPI",
    badgeText: "현",
    badgeTone: "navy",
    modelNames: ["하락장 모델"],
    modelLabel: "하락장 모델",
    decisionLabel: "기다릴 종목",
    decisionCode: "SIDE",
    reasonBullets: ["미국 판매 둔화 우려", "이익 성장 둔화"],
    cautionBullets: ["미국 금리 고정 장기화", "전기차 경쟁 심화"],
  },
  {
    assetCode: "102780",
    assetName: "KODEX 반도체",
    market: "ETF",
    badgeText: "K",
    badgeTone: "purple",
    modelNames: ["모멘텀 모델", "하락장 모델"],
    modelLabel: "여러 모델",
    decisionLabel: "조심할 종목",
    decisionCode: "WARNING",
    reasonBullets: ["단기 고점 부담", "외국인 매도"],
    cautionBullets: ["지수 조정 시 낙폭 확대", "반도체 변동성 확대"],
  },
];

export const quantReports: QuantReportSummary[] = [
  {
    id: "report-20260528-am",
    title: "오늘 시장 현황과 반도체 수급 점검",
    modelCode: "momentum-earnings",
    modelName: "모멘텀 모델",
    publishedAt: "2026.05.28 14:10",
    summary: "지수 약세 속에서도 반도체 수급 개선 흐름이 확인되어 관련 종목을 선별 점검합니다.",
    keywords: ["시장현황", "반도체", "수급"],
  },
  {
    id: "report-20260528-risk",
    title: "변동성 확대 구간에서 조심할 종목",
    modelCode: "risk-control",
    modelName: "하락장 모델",
    publishedAt: "2026.05.28 11:40",
    summary: "지수 조정과 외국인 매도가 겹친 종목은 오늘 신규 진입보다 관찰이 우선입니다.",
    keywords: ["변동성", "외국인매도", "위험관리"],
  },
];
