spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379
  sql:
    init:
      mode: always

app:
  auth:
    username: ${APP_AUTH_USERNAME:admin}
    password: ${APP_AUTH_PASSWORD}
  jwt:
    secret: ${APP_JWT_SECRET}
